### ISSUE TITLE
This repository is for typescript, need to change to javascript

### ISSUE THREAD

**Issue by MEINNASTIE** [Whit3-B3ard/Music-Player#1]

**Comment by Whit3-B3ard** [comment]
add JavaScript files to a Next.js project with TypeScript without having to delete the repository.
Update tsconfig.json:
Open your tsconfig.json file, and find the include field. Make sure it includes both TypeScript and JavaScript file extensions. It should look something like this:
{
  "compilerOptions": {
    // your compiler options...
  },
  "include": ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx"]
}
@MEINNASTIE

**Comment by MEINNASTIE** [comment]
alright.
